export {
  SPACING_BASE_LG,
  SPACING_BASE_MD,
  SPACING_BASE_SM,
  SPACING_BASE_X2L,
  SPACING_BASE_X2S,
  SPACING_BASE_X3L,
  SPACING_BASE_X4L,
  SPACING_BASE_X5L,
  SPACING_BASE_X6L,
  SPACING_BASE_X7L,
  SPACING_BASE_XL,
  SPACING_BASE_XS,
} from './spacing'
export {
  LINE_HEIGHT_BASE_LOOSE,
  LINE_HEIGHT_BASE_NONE,
  LINE_HEIGHT_BASE_NORMAL,
  LINE_HEIGHT_BASE_RELAXED,
  LINE_HEIGHT_BASE_SNUG,
  LINE_HEIGHT_BASE_TIGHT,
} from './text'
