export { TextColor } from './color'
export { TextFontSize, TextFontWeight } from './font'
export { TextRole } from './role'
export { TextAlign, TextLineHeight } from './text'
export { TEXT_TYPE_HEADING, TextType } from './type'
