'use strict'

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const SRC = path.join(ROOT, 'src')
const OUTPUT = path.join(ROOT, 'snapshot.scenes.ts')
const CREATE_CALL = /test\.create\(/
const GROUP_FROM_FILENAME = /^(.+)\.snapshot\.test\.tsx?$/
const CASE_EXPORT = /export const ([A-Z][A-Z0-9_]*)(?::\s*SnapshotCase)?\s*=\s*\[/g

function findSceneFiles(dir) {
  const results = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...findSceneFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith('.snapshot.test.tsx')) {
      results.push(fullPath)
    }
  }
  return results
}

// Namespace-import alias in the generated file, since every scene file exports its cases under the same names.
function toCamelCase(basename) {
  return basename
    .split(/[.-]/)
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('')
}

function generateScenes() {
  const sceneFiles = findSceneFiles(SRC).sort()

  const files = sceneFiles.map((filePath) => {
    const contents = fs.readFileSync(filePath, 'utf8')
    if (!CREATE_CALL.test(contents)) {
      throw new Error(`${path.relative(ROOT, filePath)} has no \`test.create('...', {...})\` call - every *.snapshot.test.tsx file must call it.`)
    }
    const caseNames = [...contents.matchAll(CASE_EXPORT)].map(([, name]) => name)
    if (caseNames.length === 0) {
      throw new Error(
        `${path.relative(ROOT, filePath)} has no \`export const <NAME>: SnapshotCase = [...]\` - every *.snapshot.test.tsx file must export at least one case.`,
      )
    }
    // Must match `createSnapshotSuite`'s route derivation in snapshot.helpers.tsx.
    const component = path.basename(path.dirname(filePath))
    const basename = path.basename(filePath, '.snapshot.test.tsx')
    const group = GROUP_FROM_FILENAME.exec(path.basename(filePath))[1].split('.').pop()
    const id = `component/${component}/${group}`
    const alias = toCamelCase(basename)
    const importPath = `@/${path.relative(SRC, filePath).replace(/\.tsx$/, '').split(path.sep).join('/')}`
    return { alias, id, caseNames, importPath }
  })

  const importLines = files.map(({ alias, importPath }) => `import * as ${alias} from '${importPath}'`).join('\n')
  const arrayItems = files
    .flatMap(({ alias, id, caseNames }) =>
      caseNames.map((caseName) => `{ id: '${id}/${caseName}', render: ${alias}.${caseName}[1] }`),
    )
    .join(', ')

  const output = `${importLines}${importLines ? '\n' : ''}import type { VisualScene } from '@root/snapshot.types'

// Generated by scripts/generate-scenes.js - do not edit or commit.
export const VISUAL_SCENES: VisualScene[] = [${arrayItems}]
`

  fs.writeFileSync(OUTPUT, output)
}

generateScenes()
