'use strict'

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const SRC = path.join(ROOT, 'src')
const OUTPUT = path.join(ROOT, 'snapshot.scenes.ts')
const SCENE_EXPORT = /export const (\w+): VisualScene = /

function findSceneFiles(dir) {
  const results = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...findSceneFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith('.snapshot.test.tsx')) {
      results.push(fullPath)
    }
  }
  return results
}

function generateScenes() {
  const sceneFiles = findSceneFiles(SRC).sort()

  const scenes = sceneFiles.map((filePath) => {
    const contents = fs.readFileSync(filePath, 'utf8')
    const match = contents.match(SCENE_EXPORT)
    if (!match) {
      throw new Error(
        `${path.relative(ROOT, filePath)} has no \`export const <NAME>: VisualScene\` - every *.snapshot.test.tsx file must export one scene.`,
      )
    }
    const importPath = `@/${path.relative(SRC, filePath).replace(/\.tsx$/, '').split(path.sep).join('/')}`
    return { name: match[1], importPath }
  })

  const importLines = scenes.map(({ name, importPath }) => `import { ${name} } from '${importPath}'`).join('\n')
  const arrayItems = scenes.map(({ name }) => name).join(', ')

  const output = `${importLines}${importLines ? '\n' : ''}import type { VisualScene } from '@root/snapshot.types'

/**
 * Generated by \`node scripts/generate-scenes.js\` from every \`*.snapshot.test.tsx\` file under \`src\`'s
 * exported \`VisualScene\` - do not edit by hand, and don't commit it (see .gitignore).
 */
export const VISUAL_SCENES: VisualScene[] = [${arrayItems}]
`

  fs.writeFileSync(OUTPUT, output)
}

generateScenes()
