'use strict'

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const SRC = path.join(ROOT, 'src')
const OUTPUT = path.join(ROOT, 'snapshot.scenes.ts')
const ID_EXPORT = /export const id = /
const SCENE_EXPORT = /export function Scene\(/

function findSceneFiles(dir) {
  const results = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...findSceneFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith('.snapshot.test.tsx')) {
      results.push(fullPath)
    }
  }
  return results
}

// `view.margin` -> `ViewMargin`, used to alias each file's `id`/`Scene` exports uniquely in the
// generated file, since every `*.snapshot.test.tsx` file exports those two names identically.
function toPascalCase(basename) {
  return basename
    .split('.')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function generateScenes() {
  const sceneFiles = findSceneFiles(SRC).sort()

  const scenes = sceneFiles.map((filePath) => {
    const contents = fs.readFileSync(filePath, 'utf8')
    if (!ID_EXPORT.test(contents) || !SCENE_EXPORT.test(contents)) {
      throw new Error(
        `${path.relative(ROOT, filePath)} has no \`export const id\`/\`export function Scene\` - every *.snapshot.test.tsx file must export both.`,
      )
    }
    const basename = path.basename(filePath, '.snapshot.test.tsx')
    const alias = toPascalCase(basename)
    const importPath = `@/${path.relative(SRC, filePath).replace(/\.tsx$/, '').split(path.sep).join('/')}`
    return { idAlias: `${alias.charAt(0).toLowerCase()}${alias.slice(1)}Id`, sceneAlias: `${alias}Scene`, importPath }
  })

  const importLines = scenes
    .map(({ idAlias, sceneAlias, importPath }) => `import { id as ${idAlias}, Scene as ${sceneAlias} } from '${importPath}'`)
    .join('\n')
  const arrayItems = scenes.map(({ idAlias, sceneAlias }) => `{ id: ${idAlias}, Scene: ${sceneAlias} }`).join(', ')

  const output = `${importLines}${importLines ? '\n' : ''}import type { VisualScene } from '@root/snapshot.types'

/**
 * Generated by \`node scripts/generate-scenes.js\` from every \`*.snapshot.test.tsx\` file under \`src\`'s
 * exported \`id\`/\`Scene\` - do not edit by hand, and don't commit it (see .gitignore).
 */
export const VISUAL_SCENES: VisualScene[] = [${arrayItems}]
`

  fs.writeFileSync(OUTPUT, output)
}

generateScenes()
