import { createContext, useContext, useMemo } from 'react'
import {
  BORDER_RADIUS_BASE_LG,
  BORDER_RADIUS_BASE_MD,
  BORDER_RADIUS_BASE_SM,
  BORDER_RADIUS_BASE_X2L,
  BORDER_RADIUS_BASE_X3L,
  BORDER_RADIUS_BASE_X4L,
  BORDER_RADIUS_BASE_X5L,
  BORDER_RADIUS_BASE_X6L,
  BORDER_RADIUS_BASE_X7L,
  BORDER_RADIUS_BASE_XL,
  BORDER_RADIUS_BASE_XS,
  BORDER_WIDTH_BASE_LG,
  BORDER_WIDTH_BASE_MD,
  BORDER_WIDTH_BASE_SM,
  BUTTON_HEIGHT_BASE_LG,
  BUTTON_HEIGHT_BASE_MD,
  BUTTON_HEIGHT_BASE_SM,
  COLOR_BACKGROUND_ACCENT_100,
  COLOR_BACKGROUND_ACCENT_200,
  COLOR_BACKGROUND_ACCENT_300,
  COLOR_BACKGROUND_ACCENT_400,
  COLOR_BACKGROUND_ACCENT_500,
  COLOR_BACKGROUND_ACCENT_600,
  COLOR_BACKGROUND_ACCENT_700,
  COLOR_BACKGROUND_ACCENT_800,
  COLOR_BACKGROUND_ACCENT_900,
  COLOR_BACKGROUND_BASE_100,
  COLOR_BACKGROUND_BASE_200,
  COLOR_BACKGROUND_BASE_300,
  COLOR_BACKGROUND_BASE_400,
  COLOR_BACKGROUND_BASE_500,
  COLOR_BACKGROUND_BASE_600,
  COLOR_BACKGROUND_BASE_700,
  COLOR_BACKGROUND_BASE_800,
  COLOR_BACKGROUND_BASE_900,
  COLOR_BACKGROUND_PRIMARY_100,
  COLOR_BACKGROUND_PRIMARY_200,
  COLOR_BACKGROUND_PRIMARY_300,
  COLOR_BACKGROUND_PRIMARY_400,
  COLOR_BACKGROUND_PRIMARY_500,
  COLOR_BACKGROUND_PRIMARY_600,
  COLOR_BACKGROUND_PRIMARY_700,
  COLOR_BACKGROUND_PRIMARY_800,
  COLOR_BACKGROUND_PRIMARY_900,
  COLOR_BACKGROUND_SUBACCENT_100,
  COLOR_BACKGROUND_SUBACCENT_200,
  COLOR_BACKGROUND_SUBACCENT_300,
  COLOR_BACKGROUND_SUBACCENT_400,
  COLOR_BACKGROUND_SUBACCENT_500,
  COLOR_BACKGROUND_SUBACCENT_600,
  COLOR_BACKGROUND_SUBACCENT_700,
  COLOR_BACKGROUND_SUBACCENT_800,
  COLOR_BACKGROUND_SUBACCENT_900,
  COLOR_BORDER_BASE_100,
  COLOR_BORDER_BASE_200,
  COLOR_BORDER_BASE_300,
  COLOR_BORDER_BASE_400,
  COLOR_BORDER_BASE_500,
  COLOR_BORDER_BASE_600,
  COLOR_BORDER_BASE_700,
  COLOR_BORDER_BASE_800,
  COLOR_BORDER_BASE_900,
  COLOR_FOREGROUND_BASE_100,
  COLOR_FOREGROUND_BASE_200,
  COLOR_FOREGROUND_BASE_300,
  COLOR_FOREGROUND_BASE_400,
  COLOR_FOREGROUND_BASE_500,
  COLOR_FOREGROUND_BASE_600,
  COLOR_FOREGROUND_BASE_700,
  COLOR_FOREGROUND_BASE_800,
  COLOR_FOREGROUND_BASE_900,
  COLOR_FOREGROUND_FAILURE_100,
  COLOR_FOREGROUND_FAILURE_200,
  COLOR_FOREGROUND_FAILURE_300,
  COLOR_FOREGROUND_FAILURE_400,
  COLOR_FOREGROUND_FAILURE_500,
  COLOR_FOREGROUND_FAILURE_600,
  COLOR_FOREGROUND_FAILURE_700,
  COLOR_FOREGROUND_FAILURE_800,
  COLOR_FOREGROUND_FAILURE_900,
  COLOR_FOREGROUND_INVERSE_100,
  COLOR_FOREGROUND_INVERSE_200,
  COLOR_FOREGROUND_INVERSE_300,
  COLOR_FOREGROUND_INVERSE_400,
  COLOR_FOREGROUND_INVERSE_500,
  COLOR_FOREGROUND_INVERSE_600,
  COLOR_FOREGROUND_INVERSE_700,
  COLOR_FOREGROUND_INVERSE_800,
  COLOR_FOREGROUND_INVERSE_900,
  DURATION_BASE_LG,
  DURATION_BASE_MD,
  DURATION_BASE_SM,
  DURATION_COMPLEX_LG,
  DURATION_COMPLEX_MD,
  DURATION_COMPLEX_SM,
  FONT_FAMILY_DEFAULT,
  FONT_FAMILY_TYPOGRAPHIC,
  FONT_SIZE_BASE_LG,
  FONT_SIZE_BASE_MD,
  FONT_SIZE_BASE_SM,
  FONT_SIZE_BASE_X2L,
  FONT_SIZE_BASE_X2S,
  FONT_SIZE_BASE_X3L,
  FONT_SIZE_BASE_X4L,
  FONT_SIZE_BASE_X5L,
  FONT_SIZE_BASE_X6L,
  FONT_SIZE_BASE_XL,
  FONT_SIZE_BASE_XS,
  FONT_WEIGHT_BASE_BLACK,
  FONT_WEIGHT_BASE_BOLD,
  FONT_WEIGHT_BASE_EXTRABOLD,
  FONT_WEIGHT_BASE_EXTRALIGHT,
  FONT_WEIGHT_BASE_LIGHT,
  FONT_WEIGHT_BASE_MEDIUM,
  FONT_WEIGHT_BASE_REGULAR,
  FONT_WEIGHT_BASE_SEMIBOLD,
  FONT_WEIGHT_BASE_THIN,
  ICON_SIZE_BASE_LG,
  ICON_SIZE_BASE_MD,
  ICON_SIZE_BASE_SM,
  LINE_HEIGHT_BASE_LOOSE,
  LINE_HEIGHT_BASE_NONE,
  LINE_HEIGHT_BASE_NORMAL,
  LINE_HEIGHT_BASE_RELAXED,
  LINE_HEIGHT_BASE_SNUG,
  LINE_HEIGHT_BASE_TIGHT,
  SPACING_BASE_LG,
  SPACING_BASE_MD,
  SPACING_BASE_SM,
  SPACING_BASE_X2L,
  SPACING_BASE_X2S,
  SPACING_BASE_X3L,
  SPACING_BASE_X3S,
  SPACING_BASE_X4L,
  SPACING_BASE_X4S,
  SPACING_BASE_X5L,
  SPACING_BASE_X5S,
  SPACING_BASE_X6L,
  SPACING_BASE_X6S,
  SPACING_BASE_XL,
  SPACING_BASE_XS,
} from './constants'
import type {
  ThemeContextProviderComponent,
  ThemeContextValue,
} from './theme.types'

// We can use context even outside provider.
// This can be helpful for testing and storybook.
const ThemeContext = createContext<ThemeContextValue>({
  colorBackgroundBase100: COLOR_BACKGROUND_BASE_100,
  colorBackgroundBase200: COLOR_BACKGROUND_BASE_200,
  colorBackgroundBase300: COLOR_BACKGROUND_BASE_300,
  colorBackgroundBase400: COLOR_BACKGROUND_BASE_400,
  colorBackgroundBase500: COLOR_BACKGROUND_BASE_500,
  colorBackgroundBase600: COLOR_BACKGROUND_BASE_600,
  colorBackgroundBase700: COLOR_BACKGROUND_BASE_700,
  colorBackgroundBase800: COLOR_BACKGROUND_BASE_800,
  colorBackgroundBase900: COLOR_BACKGROUND_BASE_900,

  colorBackgroundPrimary100: COLOR_BACKGROUND_PRIMARY_100,
  colorBackgroundPrimary200: COLOR_BACKGROUND_PRIMARY_200,
  colorBackgroundPrimary300: COLOR_BACKGROUND_PRIMARY_300,
  colorBackgroundPrimary400: COLOR_BACKGROUND_PRIMARY_400,
  colorBackgroundPrimary500: COLOR_BACKGROUND_PRIMARY_500,
  colorBackgroundPrimary600: COLOR_BACKGROUND_PRIMARY_600,
  colorBackgroundPrimary700: COLOR_BACKGROUND_PRIMARY_700,
  colorBackgroundPrimary800: COLOR_BACKGROUND_PRIMARY_800,
  colorBackgroundPrimary900: COLOR_BACKGROUND_PRIMARY_900,

  colorBackgroundAccent100: COLOR_BACKGROUND_ACCENT_100,
  colorBackgroundAccent200: COLOR_BACKGROUND_ACCENT_200,
  colorBackgroundAccent300: COLOR_BACKGROUND_ACCENT_300,
  colorBackgroundAccent400: COLOR_BACKGROUND_ACCENT_400,
  colorBackgroundAccent500: COLOR_BACKGROUND_ACCENT_500,
  colorBackgroundAccent600: COLOR_BACKGROUND_ACCENT_600,
  colorBackgroundAccent700: COLOR_BACKGROUND_ACCENT_700,
  colorBackgroundAccent800: COLOR_BACKGROUND_ACCENT_800,
  colorBackgroundAccent900: COLOR_BACKGROUND_ACCENT_900,

  colorBackgroundSubaccent100: COLOR_BACKGROUND_SUBACCENT_100,
  colorBackgroundSubaccent200: COLOR_BACKGROUND_SUBACCENT_200,
  colorBackgroundSubaccent300: COLOR_BACKGROUND_SUBACCENT_300,
  colorBackgroundSubaccent400: COLOR_BACKGROUND_SUBACCENT_400,
  colorBackgroundSubaccent500: COLOR_BACKGROUND_SUBACCENT_500,
  colorBackgroundSubaccent600: COLOR_BACKGROUND_SUBACCENT_600,
  colorBackgroundSubaccent700: COLOR_BACKGROUND_SUBACCENT_700,
  colorBackgroundSubaccent800: COLOR_BACKGROUND_SUBACCENT_800,
  colorBackgroundSubaccent900: COLOR_BACKGROUND_SUBACCENT_900,

  colorBorderBase100: COLOR_BORDER_BASE_100,
  colorBorderBase200: COLOR_BORDER_BASE_200,
  colorBorderBase300: COLOR_BORDER_BASE_300,
  colorBorderBase400: COLOR_BORDER_BASE_400,
  colorBorderBase500: COLOR_BORDER_BASE_500,
  colorBorderBase600: COLOR_BORDER_BASE_600,
  colorBorderBase700: COLOR_BORDER_BASE_700,
  colorBorderBase800: COLOR_BORDER_BASE_800,
  colorBorderBase900: COLOR_BORDER_BASE_900,

  colorForegroundBase100: COLOR_FOREGROUND_BASE_100,
  colorForegroundBase200: COLOR_FOREGROUND_BASE_200,
  colorForegroundBase300: COLOR_FOREGROUND_BASE_300,
  colorForegroundBase400: COLOR_FOREGROUND_BASE_400,
  colorForegroundBase500: COLOR_FOREGROUND_BASE_500,
  colorForegroundBase600: COLOR_FOREGROUND_BASE_600,
  colorForegroundBase700: COLOR_FOREGROUND_BASE_700,
  colorForegroundBase800: COLOR_FOREGROUND_BASE_800,
  colorForegroundBase900: COLOR_FOREGROUND_BASE_900,

  colorForegroundInverse100: COLOR_FOREGROUND_INVERSE_100,
  colorForegroundInverse200: COLOR_FOREGROUND_INVERSE_200,
  colorForegroundInverse300: COLOR_FOREGROUND_INVERSE_300,
  colorForegroundInverse400: COLOR_FOREGROUND_INVERSE_400,
  colorForegroundInverse500: COLOR_FOREGROUND_INVERSE_500,
  colorForegroundInverse600: COLOR_FOREGROUND_INVERSE_600,
  colorForegroundInverse700: COLOR_FOREGROUND_INVERSE_700,
  colorForegroundInverse800: COLOR_FOREGROUND_INVERSE_800,
  colorForegroundInverse900: COLOR_FOREGROUND_INVERSE_900,

  colorForegroundFailure100: COLOR_FOREGROUND_FAILURE_100,
  colorForegroundFailure200: COLOR_FOREGROUND_FAILURE_200,
  colorForegroundFailure300: COLOR_FOREGROUND_FAILURE_300,
  colorForegroundFailure400: COLOR_FOREGROUND_FAILURE_400,
  colorForegroundFailure500: COLOR_FOREGROUND_FAILURE_500,
  colorForegroundFailure600: COLOR_FOREGROUND_FAILURE_600,
  colorForegroundFailure700: COLOR_FOREGROUND_FAILURE_700,
  colorForegroundFailure800: COLOR_FOREGROUND_FAILURE_800,
  colorForegroundFailure900: COLOR_FOREGROUND_FAILURE_900,

  fontFamilyDefault: FONT_FAMILY_DEFAULT,
  fontFamilyTypographic: FONT_FAMILY_TYPOGRAPHIC,

  fontWeightBaseThin: FONT_WEIGHT_BASE_THIN,
  fontWeightBaseExtraLight: FONT_WEIGHT_BASE_EXTRALIGHT,
  fontWeightBaseLight: FONT_WEIGHT_BASE_LIGHT,
  fontWeightBaseRegular: FONT_WEIGHT_BASE_REGULAR,
  fontWeightBaseMedium: FONT_WEIGHT_BASE_MEDIUM,
  fontWeightBaseSemiBold: FONT_WEIGHT_BASE_SEMIBOLD,
  fontWeightBaseBold: FONT_WEIGHT_BASE_BOLD,
  fontWeightBaseExtraBold: FONT_WEIGHT_BASE_EXTRABOLD,
  fontWeightBaseBlack: FONT_WEIGHT_BASE_BLACK,

  fontSizeBaseX2S: FONT_SIZE_BASE_X2S,
  fontSizeBaseXS: FONT_SIZE_BASE_XS,
  fontSizeBaseSM: FONT_SIZE_BASE_SM,
  fontSizeBaseMD: FONT_SIZE_BASE_MD,
  fontSizeBaseLG: FONT_SIZE_BASE_LG,
  fontSizeBaseXL: FONT_SIZE_BASE_XL,
  fontSizeBaseX2L: FONT_SIZE_BASE_X2L,
  fontSizeBaseX3L: FONT_SIZE_BASE_X3L,
  fontSizeBaseX4L: FONT_SIZE_BASE_X4L,
  fontSizeBaseX5L: FONT_SIZE_BASE_X5L,
  fontSizeBaseX6L: FONT_SIZE_BASE_X6L,

  lineHeightBaseNone: LINE_HEIGHT_BASE_NONE,
  lineHeightBaseTight: LINE_HEIGHT_BASE_TIGHT,
  lineHeightBaseSnug: LINE_HEIGHT_BASE_SNUG,
  lineHeightBaseNormal: LINE_HEIGHT_BASE_NORMAL,
  lineHeightBaseRelaxed: LINE_HEIGHT_BASE_RELAXED,
  lineHeightBaseLoose: LINE_HEIGHT_BASE_LOOSE,

  spacingBaseX6S: SPACING_BASE_X6S,
  spacingBaseX5S: SPACING_BASE_X5S,
  spacingBaseX4S: SPACING_BASE_X4S,
  spacingBaseX3S: SPACING_BASE_X3S,
  spacingBaseX2S: SPACING_BASE_X2S,
  spacingBaseXS: SPACING_BASE_XS,
  spacingBaseSM: SPACING_BASE_SM,
  spacingBaseMD: SPACING_BASE_MD,
  spacingBaseLG: SPACING_BASE_LG,
  spacingBaseXL: SPACING_BASE_XL,
  spacingBaseX2L: SPACING_BASE_X2L,
  spacingBaseX3L: SPACING_BASE_X3L,
  spacingBaseX4L: SPACING_BASE_X4L,
  spacingBaseX5L: SPACING_BASE_X5L,
  spacingBaseX6L: SPACING_BASE_X6L,

  borderWidthBaseSM: BORDER_WIDTH_BASE_SM,
  borderWidthBaseMD: BORDER_WIDTH_BASE_MD,
  borderWidthBaseLG: BORDER_WIDTH_BASE_LG,

  borderRadiusBaseXS: BORDER_RADIUS_BASE_XS,
  borderRadiusBaseSM: BORDER_RADIUS_BASE_SM,
  borderRadiusBaseMD: BORDER_RADIUS_BASE_MD,
  borderRadiusBaseLG: BORDER_RADIUS_BASE_LG,
  borderRadiusBaseXL: BORDER_RADIUS_BASE_XL,
  borderRadiusBaseX2L: BORDER_RADIUS_BASE_X2L,
  borderRadiusBaseX3L: BORDER_RADIUS_BASE_X3L,
  borderRadiusBaseX4L: BORDER_RADIUS_BASE_X4L,
  borderRadiusBaseX5L: BORDER_RADIUS_BASE_X5L,
  borderRadiusBaseX6L: BORDER_RADIUS_BASE_X6L,
  borderRadiusBaseX7L: BORDER_RADIUS_BASE_X7L,

  buttonHeightBaseSM: BUTTON_HEIGHT_BASE_SM,
  buttonHeightBaseMD: BUTTON_HEIGHT_BASE_MD,
  buttonHeightBaseLG: BUTTON_HEIGHT_BASE_LG,

  iconSizeBaseSM: ICON_SIZE_BASE_SM,
  iconSizeBaseMD: ICON_SIZE_BASE_MD,
  iconSizeBaseLG: ICON_SIZE_BASE_LG,

  durationBaseSM: DURATION_BASE_SM,
  durationBaseMD: DURATION_BASE_MD,
  durationBaseLG: DURATION_BASE_LG,

  durationComplexSM: DURATION_COMPLEX_SM,
  durationComplexMD: DURATION_COMPLEX_MD,
  durationComplexLG: DURATION_COMPLEX_LG,
})

export const ThemeContextProvider: ThemeContextProviderComponent = ({
  colorBackgroundBase100,
  colorBackgroundBase200,
  colorBackgroundBase300,
  colorBackgroundBase400,
  colorBackgroundBase500,
  colorBackgroundBase600,
  colorBackgroundBase700,
  colorBackgroundBase800,
  colorBackgroundBase900,

  colorBackgroundPrimary100,
  colorBackgroundPrimary200,
  colorBackgroundPrimary300,
  colorBackgroundPrimary400,
  colorBackgroundPrimary500,
  colorBackgroundPrimary600,
  colorBackgroundPrimary700,
  colorBackgroundPrimary800,
  colorBackgroundPrimary900,

  colorBackgroundAccent100,
  colorBackgroundAccent200,
  colorBackgroundAccent300,
  colorBackgroundAccent400,
  colorBackgroundAccent500,
  colorBackgroundAccent600,
  colorBackgroundAccent700,
  colorBackgroundAccent800,
  colorBackgroundAccent900,

  colorBackgroundSubaccent100,
  colorBackgroundSubaccent200,
  colorBackgroundSubaccent300,
  colorBackgroundSubaccent400,
  colorBackgroundSubaccent500,
  colorBackgroundSubaccent600,
  colorBackgroundSubaccent700,
  colorBackgroundSubaccent800,
  colorBackgroundSubaccent900,

  colorBorderBase100,
  colorBorderBase200,
  colorBorderBase300,
  colorBorderBase400,
  colorBorderBase500,
  colorBorderBase600,
  colorBorderBase700,
  colorBorderBase800,
  colorBorderBase900,

  colorForegroundBase100,
  colorForegroundBase200,
  colorForegroundBase300,
  colorForegroundBase400,
  colorForegroundBase500,
  colorForegroundBase600,
  colorForegroundBase700,
  colorForegroundBase800,
  colorForegroundBase900,

  colorForegroundInverse100,
  colorForegroundInverse200,
  colorForegroundInverse300,
  colorForegroundInverse400,
  colorForegroundInverse500,
  colorForegroundInverse600,
  colorForegroundInverse700,
  colorForegroundInverse800,
  colorForegroundInverse900,

  colorForegroundFailure100,
  colorForegroundFailure200,
  colorForegroundFailure300,
  colorForegroundFailure400,
  colorForegroundFailure500,
  colorForegroundFailure600,
  colorForegroundFailure700,
  colorForegroundFailure800,
  colorForegroundFailure900,

  fontFamilyDefault,
  fontFamilyTypographic,

  fontWeightBaseThin,
  fontWeightBaseExtraLight,
  fontWeightBaseLight,
  fontWeightBaseRegular,
  fontWeightBaseMedium,
  fontWeightBaseSemiBold,
  fontWeightBaseBold,
  fontWeightBaseExtraBold,
  fontWeightBaseBlack,

  fontSizeBaseX2S,
  fontSizeBaseXS,
  fontSizeBaseSM,
  fontSizeBaseMD,
  fontSizeBaseLG,
  fontSizeBaseXL,
  fontSizeBaseX2L,
  fontSizeBaseX3L,
  fontSizeBaseX4L,
  fontSizeBaseX5L,
  fontSizeBaseX6L,

  lineHeightBaseNone,
  lineHeightBaseTight,
  lineHeightBaseSnug,
  lineHeightBaseNormal,
  lineHeightBaseRelaxed,
  lineHeightBaseLoose,

  spacingBaseX6S,
  spacingBaseX5S,
  spacingBaseX4S,
  spacingBaseX3S,
  spacingBaseX2S,
  spacingBaseXS,
  spacingBaseSM,
  spacingBaseMD,
  spacingBaseLG,
  spacingBaseXL,
  spacingBaseX2L,
  spacingBaseX3L,
  spacingBaseX4L,
  spacingBaseX5L,
  spacingBaseX6L,

  borderWidthBaseSM,
  borderWidthBaseMD,
  borderWidthBaseLG,

  borderRadiusBaseXS,
  borderRadiusBaseSM,
  borderRadiusBaseMD,
  borderRadiusBaseLG,
  borderRadiusBaseXL,
  borderRadiusBaseX2L,
  borderRadiusBaseX3L,
  borderRadiusBaseX4L,
  borderRadiusBaseX5L,
  borderRadiusBaseX6L,
  borderRadiusBaseX7L,

  buttonHeightBaseSM,
  buttonHeightBaseMD,
  buttonHeightBaseLG,

  iconSizeBaseSM,
  iconSizeBaseMD,
  iconSizeBaseLG,

  durationBaseSM,
  durationBaseMD,
  durationBaseLG,

  durationComplexSM,
  durationComplexMD,
  durationComplexLG,

  children,
}) => {
  // We do support 18 React version without compiler.
  // We have to memorize context values to avoid extra re-renders.
  const value = useMemo(
    () => ({
      colorBackgroundBase100:
        colorBackgroundBase100 ?? COLOR_BACKGROUND_BASE_100,
      colorBackgroundBase200:
        colorBackgroundBase200 ?? COLOR_BACKGROUND_BASE_200,
      colorBackgroundBase300:
        colorBackgroundBase300 ?? COLOR_BACKGROUND_BASE_300,
      colorBackgroundBase400:
        colorBackgroundBase400 ?? COLOR_BACKGROUND_BASE_400,
      colorBackgroundBase500:
        colorBackgroundBase500 ?? COLOR_BACKGROUND_BASE_500,
      colorBackgroundBase600:
        colorBackgroundBase600 ?? COLOR_BACKGROUND_BASE_600,
      colorBackgroundBase700:
        colorBackgroundBase700 ?? COLOR_BACKGROUND_BASE_700,
      colorBackgroundBase800:
        colorBackgroundBase800 ?? COLOR_BACKGROUND_BASE_800,
      colorBackgroundBase900:
        colorBackgroundBase900 ?? COLOR_BACKGROUND_BASE_900,

      colorBackgroundPrimary100:
        colorBackgroundPrimary100 ?? COLOR_BACKGROUND_PRIMARY_100,
      colorBackgroundPrimary200:
        colorBackgroundPrimary200 ?? COLOR_BACKGROUND_PRIMARY_200,
      colorBackgroundPrimary300:
        colorBackgroundPrimary300 ?? COLOR_BACKGROUND_PRIMARY_300,
      colorBackgroundPrimary400:
        colorBackgroundPrimary400 ?? COLOR_BACKGROUND_PRIMARY_400,
      colorBackgroundPrimary500:
        colorBackgroundPrimary500 ?? COLOR_BACKGROUND_PRIMARY_500,
      colorBackgroundPrimary600:
        colorBackgroundPrimary600 ?? COLOR_BACKGROUND_PRIMARY_600,
      colorBackgroundPrimary700:
        colorBackgroundPrimary700 ?? COLOR_BACKGROUND_PRIMARY_700,
      colorBackgroundPrimary800:
        colorBackgroundPrimary800 ?? COLOR_BACKGROUND_PRIMARY_800,
      colorBackgroundPrimary900:
        colorBackgroundPrimary900 ?? COLOR_BACKGROUND_PRIMARY_900,

      colorBackgroundAccent100:
        colorBackgroundAccent100 ?? COLOR_BACKGROUND_ACCENT_100,
      colorBackgroundAccent200:
        colorBackgroundAccent200 ?? COLOR_BACKGROUND_ACCENT_200,
      colorBackgroundAccent300:
        colorBackgroundAccent300 ?? COLOR_BACKGROUND_ACCENT_300,
      colorBackgroundAccent400:
        colorBackgroundAccent400 ?? COLOR_BACKGROUND_ACCENT_400,
      colorBackgroundAccent500:
        colorBackgroundAccent500 ?? COLOR_BACKGROUND_ACCENT_500,
      colorBackgroundAccent600:
        colorBackgroundAccent600 ?? COLOR_BACKGROUND_ACCENT_600,
      colorBackgroundAccent700:
        colorBackgroundAccent700 ?? COLOR_BACKGROUND_ACCENT_700,
      colorBackgroundAccent800:
        colorBackgroundAccent800 ?? COLOR_BACKGROUND_ACCENT_800,
      colorBackgroundAccent900:
        colorBackgroundAccent900 ?? COLOR_BACKGROUND_ACCENT_900,

      colorBackgroundSubaccent100:
        colorBackgroundSubaccent100 ?? COLOR_BACKGROUND_SUBACCENT_100,
      colorBackgroundSubaccent200:
        colorBackgroundSubaccent200 ?? COLOR_BACKGROUND_SUBACCENT_200,
      colorBackgroundSubaccent300:
        colorBackgroundSubaccent300 ?? COLOR_BACKGROUND_SUBACCENT_300,
      colorBackgroundSubaccent400:
        colorBackgroundSubaccent400 ?? COLOR_BACKGROUND_SUBACCENT_400,
      colorBackgroundSubaccent500:
        colorBackgroundSubaccent500 ?? COLOR_BACKGROUND_SUBACCENT_500,
      colorBackgroundSubaccent600:
        colorBackgroundSubaccent600 ?? COLOR_BACKGROUND_SUBACCENT_600,
      colorBackgroundSubaccent700:
        colorBackgroundSubaccent700 ?? COLOR_BACKGROUND_SUBACCENT_700,
      colorBackgroundSubaccent800:
        colorBackgroundSubaccent800 ?? COLOR_BACKGROUND_SUBACCENT_800,
      colorBackgroundSubaccent900:
        colorBackgroundSubaccent900 ?? COLOR_BACKGROUND_SUBACCENT_900,

      colorBorderBase100: colorBorderBase100 ?? COLOR_BORDER_BASE_100,
      colorBorderBase200: colorBorderBase200 ?? COLOR_BORDER_BASE_200,
      colorBorderBase300: colorBorderBase300 ?? COLOR_BORDER_BASE_300,
      colorBorderBase400: colorBorderBase400 ?? COLOR_BORDER_BASE_400,
      colorBorderBase500: colorBorderBase500 ?? COLOR_BORDER_BASE_500,
      colorBorderBase600: colorBorderBase600 ?? COLOR_BORDER_BASE_600,
      colorBorderBase700: colorBorderBase700 ?? COLOR_BORDER_BASE_700,
      colorBorderBase800: colorBorderBase800 ?? COLOR_BORDER_BASE_800,
      colorBorderBase900: colorBorderBase900 ?? COLOR_BORDER_BASE_900,

      colorForegroundBase100:
        colorForegroundBase100 ?? COLOR_FOREGROUND_BASE_100,
      colorForegroundBase200:
        colorForegroundBase200 ?? COLOR_FOREGROUND_BASE_200,
      colorForegroundBase300:
        colorForegroundBase300 ?? COLOR_FOREGROUND_BASE_300,
      colorForegroundBase400:
        colorForegroundBase400 ?? COLOR_FOREGROUND_BASE_400,
      colorForegroundBase500:
        colorForegroundBase500 ?? COLOR_FOREGROUND_BASE_500,
      colorForegroundBase600:
        colorForegroundBase600 ?? COLOR_FOREGROUND_BASE_600,
      colorForegroundBase700:
        colorForegroundBase700 ?? COLOR_FOREGROUND_BASE_700,
      colorForegroundBase800:
        colorForegroundBase800 ?? COLOR_FOREGROUND_BASE_800,
      colorForegroundBase900:
        colorForegroundBase900 ?? COLOR_FOREGROUND_BASE_900,

      colorForegroundInverse100:
        colorForegroundInverse100 ?? COLOR_FOREGROUND_INVERSE_100,
      colorForegroundInverse200:
        colorForegroundInverse200 ?? COLOR_FOREGROUND_INVERSE_200,
      colorForegroundInverse300:
        colorForegroundInverse300 ?? COLOR_FOREGROUND_INVERSE_300,
      colorForegroundInverse400:
        colorForegroundInverse400 ?? COLOR_FOREGROUND_INVERSE_400,
      colorForegroundInverse500:
        colorForegroundInverse500 ?? COLOR_FOREGROUND_INVERSE_500,
      colorForegroundInverse600:
        colorForegroundInverse600 ?? COLOR_FOREGROUND_INVERSE_600,
      colorForegroundInverse700:
        colorForegroundInverse700 ?? COLOR_FOREGROUND_INVERSE_700,
      colorForegroundInverse800:
        colorForegroundInverse800 ?? COLOR_FOREGROUND_INVERSE_800,
      colorForegroundInverse900:
        colorForegroundInverse900 ?? COLOR_FOREGROUND_INVERSE_900,

      colorForegroundFailure100:
        colorForegroundFailure100 ?? COLOR_FOREGROUND_FAILURE_100,
      colorForegroundFailure200:
        colorForegroundFailure200 ?? COLOR_FOREGROUND_FAILURE_200,
      colorForegroundFailure300:
        colorForegroundFailure300 ?? COLOR_FOREGROUND_FAILURE_300,
      colorForegroundFailure400:
        colorForegroundFailure400 ?? COLOR_FOREGROUND_FAILURE_400,
      colorForegroundFailure500:
        colorForegroundFailure500 ?? COLOR_FOREGROUND_FAILURE_500,
      colorForegroundFailure600:
        colorForegroundFailure600 ?? COLOR_FOREGROUND_FAILURE_600,
      colorForegroundFailure700:
        colorForegroundFailure700 ?? COLOR_FOREGROUND_FAILURE_700,
      colorForegroundFailure800:
        colorForegroundFailure800 ?? COLOR_FOREGROUND_FAILURE_800,
      colorForegroundFailure900:
        colorForegroundFailure900 ?? COLOR_FOREGROUND_FAILURE_900,

      fontFamilyDefault: fontFamilyDefault ?? FONT_FAMILY_DEFAULT,
      fontFamilyTypographic: fontFamilyTypographic ?? FONT_FAMILY_TYPOGRAPHIC,

      fontWeightBaseThin: fontWeightBaseThin ?? FONT_WEIGHT_BASE_THIN,
      fontWeightBaseExtraLight:
        fontWeightBaseExtraLight ?? FONT_WEIGHT_BASE_EXTRALIGHT,
      fontWeightBaseLight: fontWeightBaseLight ?? FONT_WEIGHT_BASE_LIGHT,
      fontWeightBaseRegular: fontWeightBaseRegular ?? FONT_WEIGHT_BASE_REGULAR,
      fontWeightBaseMedium: fontWeightBaseMedium ?? FONT_WEIGHT_BASE_MEDIUM,
      fontWeightBaseSemiBold:
        fontWeightBaseSemiBold ?? FONT_WEIGHT_BASE_SEMIBOLD,
      fontWeightBaseBold: fontWeightBaseBold ?? FONT_WEIGHT_BASE_BOLD,
      fontWeightBaseExtraBold:
        fontWeightBaseExtraBold ?? FONT_WEIGHT_BASE_EXTRABOLD,
      fontWeightBaseBlack: fontWeightBaseBlack ?? FONT_WEIGHT_BASE_BLACK,

      fontSizeBaseX2S: fontSizeBaseX2S ?? FONT_SIZE_BASE_X2S,
      fontSizeBaseXS: fontSizeBaseXS ?? FONT_SIZE_BASE_XS,
      fontSizeBaseSM: fontSizeBaseSM ?? FONT_SIZE_BASE_SM,
      fontSizeBaseMD: fontSizeBaseMD ?? FONT_SIZE_BASE_MD,
      fontSizeBaseLG: fontSizeBaseLG ?? FONT_SIZE_BASE_LG,
      fontSizeBaseXL: fontSizeBaseXL ?? FONT_SIZE_BASE_XL,
      fontSizeBaseX2L: fontSizeBaseX2L ?? FONT_SIZE_BASE_X2L,
      fontSizeBaseX3L: fontSizeBaseX3L ?? FONT_SIZE_BASE_X3L,
      fontSizeBaseX4L: fontSizeBaseX4L ?? FONT_SIZE_BASE_X4L,
      fontSizeBaseX5L: fontSizeBaseX5L ?? FONT_SIZE_BASE_X5L,
      fontSizeBaseX6L: fontSizeBaseX6L ?? FONT_SIZE_BASE_X6L,

      lineHeightBaseNone: lineHeightBaseNone ?? LINE_HEIGHT_BASE_NONE,
      lineHeightBaseTight: lineHeightBaseTight ?? LINE_HEIGHT_BASE_TIGHT,
      lineHeightBaseSnug: lineHeightBaseSnug ?? LINE_HEIGHT_BASE_SNUG,
      lineHeightBaseNormal: lineHeightBaseNormal ?? LINE_HEIGHT_BASE_NORMAL,
      lineHeightBaseRelaxed: lineHeightBaseRelaxed ?? LINE_HEIGHT_BASE_RELAXED,
      lineHeightBaseLoose: lineHeightBaseLoose ?? LINE_HEIGHT_BASE_LOOSE,

      spacingBaseX6S: spacingBaseX6S ?? SPACING_BASE_X6S,
      spacingBaseX5S: spacingBaseX5S ?? SPACING_BASE_X5S,
      spacingBaseX4S: spacingBaseX4S ?? SPACING_BASE_X4S,
      spacingBaseX3S: spacingBaseX3S ?? SPACING_BASE_X3S,
      spacingBaseX2S: spacingBaseX2S ?? SPACING_BASE_X2S,
      spacingBaseXS: spacingBaseXS ?? SPACING_BASE_XS,
      spacingBaseSM: spacingBaseSM ?? SPACING_BASE_SM,
      spacingBaseMD: spacingBaseMD ?? SPACING_BASE_MD,
      spacingBaseLG: spacingBaseLG ?? SPACING_BASE_LG,
      spacingBaseXL: spacingBaseXL ?? SPACING_BASE_XL,
      spacingBaseX2L: spacingBaseX2L ?? SPACING_BASE_X2L,
      spacingBaseX3L: spacingBaseX3L ?? SPACING_BASE_X3L,
      spacingBaseX4L: spacingBaseX4L ?? SPACING_BASE_X4L,
      spacingBaseX5L: spacingBaseX5L ?? SPACING_BASE_X5L,
      spacingBaseX6L: spacingBaseX6L ?? SPACING_BASE_X6L,

      borderWidthBaseSM: borderWidthBaseSM ?? BORDER_WIDTH_BASE_SM,
      borderWidthBaseMD: borderWidthBaseMD ?? BORDER_WIDTH_BASE_MD,
      borderWidthBaseLG: borderWidthBaseLG ?? BORDER_WIDTH_BASE_LG,

      borderRadiusBaseXS: borderRadiusBaseXS ?? BORDER_RADIUS_BASE_XS,
      borderRadiusBaseSM: borderRadiusBaseSM ?? BORDER_RADIUS_BASE_SM,
      borderRadiusBaseMD: borderRadiusBaseMD ?? BORDER_RADIUS_BASE_MD,
      borderRadiusBaseLG: borderRadiusBaseLG ?? BORDER_RADIUS_BASE_LG,
      borderRadiusBaseXL: borderRadiusBaseXL ?? BORDER_RADIUS_BASE_XL,
      borderRadiusBaseX2L: borderRadiusBaseX2L ?? BORDER_RADIUS_BASE_X2L,
      borderRadiusBaseX3L: borderRadiusBaseX3L ?? BORDER_RADIUS_BASE_X3L,
      borderRadiusBaseX4L: borderRadiusBaseX4L ?? BORDER_RADIUS_BASE_X4L,
      borderRadiusBaseX5L: borderRadiusBaseX5L ?? BORDER_RADIUS_BASE_X5L,
      borderRadiusBaseX6L: borderRadiusBaseX6L ?? BORDER_RADIUS_BASE_X6L,
      borderRadiusBaseX7L: borderRadiusBaseX7L ?? BORDER_RADIUS_BASE_X7L,

      buttonHeightBaseSM: buttonHeightBaseSM ?? BUTTON_HEIGHT_BASE_SM,
      buttonHeightBaseMD: buttonHeightBaseMD ?? BUTTON_HEIGHT_BASE_MD,
      buttonHeightBaseLG: buttonHeightBaseLG ?? BUTTON_HEIGHT_BASE_LG,

      iconSizeBaseSM: iconSizeBaseSM ?? ICON_SIZE_BASE_SM,
      iconSizeBaseMD: iconSizeBaseMD ?? ICON_SIZE_BASE_MD,
      iconSizeBaseLG: iconSizeBaseLG ?? ICON_SIZE_BASE_LG,

      durationBaseSM: durationBaseSM ?? DURATION_BASE_SM,
      durationBaseMD: durationBaseMD ?? DURATION_BASE_MD,
      durationBaseLG: durationBaseLG ?? DURATION_BASE_LG,

      durationComplexSM: durationComplexSM ?? DURATION_COMPLEX_SM,
      durationComplexMD: durationComplexMD ?? DURATION_COMPLEX_MD,
      durationComplexLG: durationComplexLG ?? DURATION_COMPLEX_LG,
    }),
    [
      colorBackgroundBase100,
      colorBackgroundBase200,
      colorBackgroundBase300,
      colorBackgroundBase400,
      colorBackgroundBase500,
      colorBackgroundBase600,
      colorBackgroundBase700,
      colorBackgroundBase800,
      colorBackgroundBase900,

      colorBackgroundPrimary100,
      colorBackgroundPrimary200,
      colorBackgroundPrimary300,
      colorBackgroundPrimary400,
      colorBackgroundPrimary500,
      colorBackgroundPrimary600,
      colorBackgroundPrimary700,
      colorBackgroundPrimary800,
      colorBackgroundPrimary900,

      colorBackgroundAccent100,
      colorBackgroundAccent200,
      colorBackgroundAccent300,
      colorBackgroundAccent400,
      colorBackgroundAccent500,
      colorBackgroundAccent600,
      colorBackgroundAccent700,
      colorBackgroundAccent800,
      colorBackgroundAccent900,

      colorBackgroundSubaccent100,
      colorBackgroundSubaccent200,
      colorBackgroundSubaccent300,
      colorBackgroundSubaccent400,
      colorBackgroundSubaccent500,
      colorBackgroundSubaccent600,
      colorBackgroundSubaccent700,
      colorBackgroundSubaccent800,
      colorBackgroundSubaccent900,

      colorBorderBase100,
      colorBorderBase200,
      colorBorderBase300,
      colorBorderBase400,
      colorBorderBase500,
      colorBorderBase600,
      colorBorderBase700,
      colorBorderBase800,
      colorBorderBase900,

      colorForegroundBase100,
      colorForegroundBase200,
      colorForegroundBase300,
      colorForegroundBase400,
      colorForegroundBase500,
      colorForegroundBase600,
      colorForegroundBase700,
      colorForegroundBase800,
      colorForegroundBase900,

      colorForegroundInverse100,
      colorForegroundInverse200,
      colorForegroundInverse300,
      colorForegroundInverse400,
      colorForegroundInverse500,
      colorForegroundInverse600,
      colorForegroundInverse700,
      colorForegroundInverse800,
      colorForegroundInverse900,

      colorForegroundFailure100,
      colorForegroundFailure200,
      colorForegroundFailure300,
      colorForegroundFailure400,
      colorForegroundFailure500,
      colorForegroundFailure600,
      colorForegroundFailure700,
      colorForegroundFailure800,
      colorForegroundFailure900,

      fontFamilyDefault,
      fontFamilyTypographic,

      fontWeightBaseThin,
      fontWeightBaseExtraLight,
      fontWeightBaseLight,
      fontWeightBaseRegular,
      fontWeightBaseMedium,
      fontWeightBaseSemiBold,
      fontWeightBaseBold,
      fontWeightBaseExtraBold,
      fontWeightBaseBlack,

      fontSizeBaseX2S,
      fontSizeBaseXS,
      fontSizeBaseSM,
      fontSizeBaseMD,
      fontSizeBaseLG,
      fontSizeBaseXL,
      fontSizeBaseX2L,
      fontSizeBaseX3L,
      fontSizeBaseX4L,
      fontSizeBaseX5L,
      fontSizeBaseX6L,

      lineHeightBaseNone,
      lineHeightBaseTight,
      lineHeightBaseSnug,
      lineHeightBaseNormal,
      lineHeightBaseRelaxed,
      lineHeightBaseLoose,

      spacingBaseX6S,
      spacingBaseX5S,
      spacingBaseX4S,
      spacingBaseX3S,
      spacingBaseX2S,
      spacingBaseXS,
      spacingBaseSM,
      spacingBaseMD,
      spacingBaseLG,
      spacingBaseXL,
      spacingBaseX2L,
      spacingBaseX3L,
      spacingBaseX4L,
      spacingBaseX5L,
      spacingBaseX6L,

      borderWidthBaseSM,
      borderWidthBaseMD,
      borderWidthBaseLG,

      borderRadiusBaseXS,
      borderRadiusBaseSM,
      borderRadiusBaseMD,
      borderRadiusBaseLG,
      borderRadiusBaseXL,
      borderRadiusBaseX2L,
      borderRadiusBaseX3L,
      borderRadiusBaseX4L,
      borderRadiusBaseX5L,
      borderRadiusBaseX6L,
      borderRadiusBaseX7L,

      buttonHeightBaseSM,
      buttonHeightBaseMD,
      buttonHeightBaseLG,

      iconSizeBaseSM,
      iconSizeBaseMD,
      iconSizeBaseLG,

      durationBaseSM,
      durationBaseMD,
      durationBaseLG,

      durationComplexSM,
      durationComplexMD,
      durationComplexLG,
    ],
  )
  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>
}
export const useThemeContext = () => useContext(ThemeContext)
